#version 430
layout(local_size_x = 1, local_size_y = 1) in;

layout(rgba32f) uniform image2D img_in;
layout(rgba32f) uniform image2D img_out;

void main() {
    // get index in global work group i.e x,y position
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(img_in); 

    vec4 pixel = imageLoad(img_in, pixel_coords);

    // output to a specific pixel in the image
    imageStore(img_out, pixel_coords, vec4(pixel.x, 0.0, 0.0, 1.0));
}